# Generated by Django 3.1.5 on 2021-01-29 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=1024)),
                ('text', models.TextField(blank=True, default='')),
            ],
        ),
    ]
